<?php
class ShoppingAction extends CommonAction
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $config=D('Setting')->fetchAll();
        $this->assign('config',$config);
    }


    //显示
    public function index(){
        $aready = (int) $this->_param('aready');
        $this->assign('aready', $aready);
        $this->display();
    }

    //加载
    public function shoppingloading(){
        $youhui = D('CollarEleStoreMarket');
        import('ORG.Util.Page');
        //$map = array('user_id' => $this->uid,'softdel'=>1);
        $map = array('user_id' => $this->uid,'user_colse'=>0);
        $aready = (int) $this->_param('aready');
        if ($aready == 2) {
            $map['is_use'] = array('egt', 1);
        } elseif ($aready == 1) {
            $map['is_use'] = 0;
        } else {
            $aready == null;
        }
        $count = $youhui->where($map)->count();
        $Page = new Page($count, 25);
        $show = $Page->show();
        $var = C('VAR_PAGE') ? C('VAR_PAGE') : 'p';
        $p = $_GET[$var];
        if ($Page->totalPages < $p) {
            die('0');
        }
        $list = $youhui->where($map)->order('is_use asc')->limit($Page->firstRow . ',' . $Page->listRows)->select();
        $coupon_ids = array();
        foreach ($list as $k => $val) {
            $coupon_ids[$val['shopping_id']] = $val['shopping_id'];
        }

        $coupon = D('ShoppingEleStoreMarket')->itemsByIds($coupon_ids);
        $this->assign('coupon', $coupon);
        $this->assign('list', $list);
        $this->assign('page', $show);
        $this->display();

    }

    //删除
    public function del($id){
        $id = (int) $id;
        if (empty($id)) {
            $this->error('该购物券不存在');
        }
        if (!($detail = D('CollarEleStoreMarket')->find($id))) {
            $this->error('该购物券不存在');
        }
        if ($detail['user_id'] != $this->uid) {
            $this->error('请不要操作别人的购物券');
        }
        //D('Coupondownload')->delete($download_id);
        D('CollarEleStoreMarket')->where(array('id'=>$id))->save(array('user_colse'=>1));
        $this->success('删除成功', U('shopping/index'));
    }




}